"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import {
  ShieldCheck,
  Lock,
  FileText,
  Cookie,
  UserCheck,
  Building2,
  Mail,
  Phone,
  MapPin,
  CheckCircle2,
  ArrowRight,
  HelpCircle,
} from "lucide-react";

export default function PrivacyPolicyComponent() {
  const [activeSection, setActiveSection] = useState<string>("electronic-record");

  // Scroll Spy to highlight active section on scroll
  useEffect(() => {
    const handleScroll = () => {
      const sectionIds = [
        "electronic-record",
        "user-acceptance",
        "security-transactions",
        "collection-information",
        "data-sharing",
        "cookies-policy",
      ];

      const scrollPosition = window.scrollY + 180;

      for (const id of sectionIds) {
        const element = document.getElementById(id);
        if (element) {
          const top = element.offsetTop;
          const height = element.offsetHeight;
          if (scrollPosition >= top && scrollPosition < top + height) {
            setActiveSection(id);
            break;
          }
        }
      }
    };

    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const sections = [
    {
      id: "electronic-record",
      title: "1. Electronic Record & Legal Framework",
      icon: FileText,
      content: (
        <>
          <p className="leading-relaxed text-zinc-700 font-light text-[15px] sm:text-[16px]">
            This document is an electronic record in terms of the{" "}
            <strong className="font-semibold text-zinc-900">
              Information Technology Act, 2000
            </strong>{" "}
            and rules thereunder as applicable, along with amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
        </>
      ),
    },
    {
      id: "user-acceptance",
      title: "2. User Acceptance & Terms of Use",
      icon: UserCheck,
      content: (
        <div className="space-y-4 text-zinc-700 font-light text-[15px] sm:text-[16px] leading-relaxed">
          <p>
            The use of the Website by the User is solely governed by this Policy as well as the{" "}
            <strong className="font-semibold text-zinc-900">Terms of Use</strong> of the Website (&ldquo;Terms&rdquo;, available at www.jhamtani.com), and any modifications or amendments made thereto by the Company from time to time, at its sole discretion. Visiting the home page of the Website and/or using any of the services provided on the Website shall be deemed to signify the User&apos;s unequivocal acceptance of this Policy and the aforementioned Terms, and the User expressly agrees to be bound by the same.
          </p>
          <p>
            The User expressly agrees and acknowledges that the Terms and Policy are co-terminus, and that expiry / termination of either one will lead to the termination of the other. The User unequivocally agrees that this Policy and the aforementioned Terms constitute a legally binding agreement between the User and the Company, and that the User shall be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by the Website, and that the same shall be deemed to be incorporated into the Terms, and shall be treated as part and parcel of the same.
          </p>
          <p>
            The User acknowledges and agrees that no signature or express act is required to make these Terms and the Policy binding on the User, and that the User&apos;s act of visiting any part of the Website constitutes the User&apos;s full and final acceptance of the Policy and the aforementioned Terms.
          </p>
          <p>
            The Parties expressly agree that the Company retains the sole and exclusive right to amend or modify the Policy and the aforementioned Terms without any prior permission or intimation to the User, and the User expressly agrees that any such amendments or modifications shall come into effect immediately. The User has a duty to periodically check the Policy and Terms, and stay updated on their provisions and requirements. If the User continues to use the Website following such a change, the User will be deemed to have consented to any and all amendments / modifications made to the Policy and Terms. In so far as the User complies with the Policy and Terms, he/she is granted a personal, non-exclusive, non-transferable, revocable, limited privilege to enter, access and use the Website.
          </p>
        </div>
      ),
    },
    {
      id: "security-transactions",
      title: "3. Secure Transactions & Payment Privacy",
      icon: Lock,
      content: (
        <div className="space-y-4 text-zinc-700 font-light text-[15px] sm:text-[16px] leading-relaxed">
          <p>
            Transactions on the Website are secure and protected. Any information entered by the User when transacting on the Website is encrypted to protect the User against unintentional disclosure to third parties.
          </p>
          <p>
            The User&apos;s credit and debit card information is not received, stored by, or retained by the Company / Website in any manner. This information is supplied by the User directly to the relevant payment gateway which is authorized to handle the information provided, and is compliant with the regulations and requirements of various banks and institutions and payment franchisees that it is associated with.
          </p>
        </div>
      ),
    },
    {
      id: "collection-information",
      title: "4. Information Collection & Communication Rights",
      icon: ShieldCheck,
      content: (
        <div className="space-y-4 text-zinc-700 font-light text-[15px] sm:text-[16px] leading-relaxed">
          <p>
            When you voluntarily visit our website or send us electronic mail, we will keep a record of this information so that we can respond to you. We only collect information from you when you register on our site or fill out a form.
          </p>
          <p>
            Also, when filling out a form on our site, you may be asked to enter your: <strong className="font-semibold text-zinc-900">Name, E-mail address, or Phone number</strong>. You may, however, visit our site anonymously.
          </p>
          <div className="p-4 sm:p-5 rounded-2xl bg-[#F3ECE4] border border-[#A0725B]/30 my-4 text-zinc-900 text-sm font-medium">
            In case you have submitted your personal information and contact details, we reserve the rights to <strong className="text-[#A0725B]">Call, SMS, Email, or WhatsApp</strong> about our products, project launches, and offers, even if your number has DND (Do Not Disturb) activated on it.
          </div>
        </div>
      ),
    },
    {
      id: "data-sharing",
      title: "5. Information Sharing, Disclosure & Transfers",
      icon: Building2,
      content: (
        <div className="space-y-4 text-zinc-700 font-light text-[15px] sm:text-[16px] leading-relaxed">
          <p>
            The User is aware that the Website/Company may share the User&apos;s personal information with other corporate entities and affiliates to help detect and prevent identity theft, fraud and other potentially illegal acts; correlate related or multiple accounts to prevent abuse of the Website&apos;s services; and to facilitate joint or co-branded services, where such services are provided by more than one corporate entity.
          </p>
          <p>
            The User is aware that the Website/Company may disclose personal information if required to do so by law or if the Website/Company in good faith believes that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal processes. The Website/Company may also disclose the User&apos;s personal information to law enforcement offices, third party rights owners, or other third parties if it believes that such disclosure is reasonably necessary to enforce the Terms or Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of its users, or the general public.
          </p>
          <p>
            The User is further aware that the Website/Company and its affiliates may share / sell some or all of the User&apos;s personal information with other business entities should the Company/Website (or its assets) plan to merge with, or be acquired by such business entity, or in the event of reorganization, amalgamation, or restructuring of the Company&apos;s business. Such business entities or new entities will continue to be bound by the Terms and Policy, as may be amended from time to time.
          </p>
        </div>
      ),
    },
    {
      id: "cookies-policy",
      title: "6. Cookies & Tracking Technologies",
      icon: Cookie,
      content: (
        <div className="space-y-4 text-zinc-700 font-light text-[15px] sm:text-[16px] leading-relaxed">
          <p>
            The User is aware that a cookie is a small piece of information stored by a web server on a web browser so it can later be traced back from that particular browser, and that cookies are useful for enabling the browser to remember information specific to a given user, including but not limited to a User&apos;s login identification, password, etc.
          </p>
          <p>
            The User is aware that the Website places both permanent and temporary cookies in the User&apos;s computer&apos;s hard drive and web browser, and does hereby expressly consent to the same.
          </p>
          <p>
            The User is further aware that the Website uses data collection devices such as cookies on certain pages of the Website to help analyze web page flow, measure promotional effectiveness, and promote trust and safety, and that certain features of the Website are only available through the use of such cookies. While the User is free to decline the Website&apos;s cookies if the User&apos;s browser permits, the User may consequently be unable to use certain features on the Website.
          </p>
        </div>
      ),
    },
  ];

  return (
    <section className="relative w-full bg-[#FAF5F0] text-zinc-900 min-h-screen select-none pb-28">
      {/* 1. Page Title Hero Banner */}
      <div className="relative w-full h-[320px] sm:h-[380px] lg:h-[420px] flex items-center justify-center text-center px-6 overflow-hidden">
        {/* Background Banner Image */}
        <div className="absolute inset-0 z-0">
          <Image
            src="/assets/privacy.webp"
            alt="Jhamtani Privacy Policy Banner"
            fill
            priority
            quality={90}
            className="object-cover"
          />
          {/* Dark Overlay */}
          <div className="absolute inset-0 bg-black/65 backdrop-blur-[1px]" />
          <div className="absolute bottom-0 left-0 right-0 h-[1px] bg-gradient-to-r from-transparent via-[#C5A880]/60 to-transparent" />
        </div>

        <div className="relative z-10 max-w-4xl flex flex-col items-center pt-8">
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="font-serif font-light text-[40px] sm:text-[54px] lg:text-[66px] text-[#C5A880] tracking-[0.2em] leading-none uppercase"
          >
            PRIVACY POLICY
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="font-sans text-[11px] sm:text-xs tracking-[0.25em] text-zinc-300 uppercase mt-5 font-light max-w-2xl leading-relaxed"
          >
            Legal Terms, Data Protection &amp; Confidentiality Standards
          </motion.p>
        </div>
      </div>

      {/* 2. Main Content Container */}
      <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-12 mt-12 sm:mt-16">
        
        {/* 3. Main Policy Layout: Sidebar + Sections */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-14 items-start relative">
          
          {/* Left Sticky Navigation Column */}
          <aside className="lg:col-span-4 lg:sticky lg:top-28 self-start space-y-6 z-20">
            <div className="p-6 rounded-3xl bg-[#F3ECE4] border border-[#A0725B]/25 shadow-sm">
              <h3 className="font-serif text-lg font-semibold text-zinc-900 mb-4 pb-3 border-b border-[#A0725B]/20">
                Policy Sections
              </h3>
              <nav className="space-y-1.5">
                {sections.map((sec) => {
                  const Icon = sec.icon;
                  const isActive = activeSection === sec.id;
                  return (
                    <a
                      key={sec.id}
                      href={`#${sec.id}`}
                      onClick={() => setActiveSection(sec.id)}
                      className={`flex items-center gap-3 px-3.5 py-2.5 rounded-xl text-xs font-medium transition-all duration-300 ${
                        isActive
                          ? "bg-[#A0725B] text-white shadow-md font-semibold"
                          : "text-zinc-700 hover:bg-white/80 hover:text-[#A0725B]"
                      }`}
                    >
                      <Icon className="w-4 h-4 shrink-0" />
                      <span className="line-clamp-1">{sec.title}</span>
                    </a>
                  );
                })}
              </nav>
            </div>
          </aside>

          {/* Right Policy Document Content */}
          <div className="lg:col-span-8 space-y-8">
            {sections.map((sec, idx) => {
              const Icon = sec.icon;
              return (
                <motion.article
                  key={sec.id}
                  id={sec.id}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-80px" }}
                  transition={{ duration: 0.5, delay: idx * 0.05 }}
                  className="p-8 sm:p-10 rounded-3xl bg-white border border-[#A0725B]/20 shadow-sm hover:shadow-md transition-shadow scroll-mt-28"
                >
                  <div className="flex items-center gap-3.5 pb-5 mb-6 border-b border-[#A0725B]/15">
                    <div className="w-11 h-11 rounded-xl bg-[#FAF5F0] text-[#A0725B] flex items-center justify-center border border-[#A0725B]/20 shrink-0">
                      <Icon className="w-5 h-5" />
                    </div>
                    <h2 className="font-serif text-xl sm:text-2xl text-zinc-900 font-normal">
                      {sec.title}
                    </h2>
                  </div>

                  <div className="text-zinc-700">{sec.content}</div>
                </motion.article>
              );
            })}

            {/* Corporate Office Address Footer */}
            <div className="p-8 rounded-3xl bg-[#F3ECE4] border border-[#A0725B]/25 space-y-3 text-left">
              <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-[#A0725B]">
                <MapPin className="w-4 h-4" />
                <span>Head Office &amp; Corporate Address</span>
              </div>
              <p className="font-serif text-lg text-zinc-900 font-medium">
                Jhamtani Real Estate Developers
              </p>
              <p className="text-xs text-zinc-600 font-light leading-relaxed">
                Office No. 1303 / 1309, Nandan Probiz, Balewadi High Street, Baner, Pune, Maharashtra 411045
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
